insert into WEAPON_TYPE(EQUIPMENT_TYPE) VALUES ('TWO_HAND')
insert into WEAPON_TYPE(EQUIPMENT_TYPE) VALUES ('ONE_HAND')

insert into ARMOR_TYPE(EQUIPMENT_TYPE) VALUES ('LIGHT')
insert into ARMOR_TYPE(EQUIPMENT_TYPE) VALUES ('HEAVY')

insert into ARMOR_BODY_PLACE(PLACE) VALUES ('HEAD')
insert into ARMOR_BODY_PLACE(PLACE) VALUES ('BODY')
insert into ARMOR_BODY_PLACE(PLACE) VALUES ('HANDS')
insert into ARMOR_BODY_PLACE(PLACE) VALUES ('LEGS')


